version: '3.8'

services:
  api:
    build: 
      dockerfile: Dockerfile
    container_name: thermoprops_api
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
      # hotreload yapabilmek için volumes kaısmında appi belirmetmemiz ve command kısmında uvicornu --reload ile başlatmamız gerekir.
      # "ro" tag'ı ReadOnly kısaltmasıdır ve container'ın sadece yapılan değişikleri uygulamasını
      # belirtir (container içerisinden app'te değişik yapılmayacağı ve containerın sadece okuma yapacağı bildirilir.)
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    # - <port on localhost>:<port on container>
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=devPostgresPassword
      - DATABASE_NAME=thermoprops_db
      - DATABASE_USERNAME=postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=devPostgresPassword
      - POSTGRES_DB=thermoprops_db
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

volumes:
  postgres_data:
    driver: local
      
networks:
  postgres:
    driver: bridge

