version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: thermoprops_frontend
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
            - ./frontend:/usr/src/app  # Yalnızca gerekli dizini bağlayın
            - /usr/src/app/node_modules
            - ./frontend/node_modules:/usr/src/app/node_modules
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: thermoprops_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

networks:
  mynetwork:
    driver: bridge


#version: '3.8'
#
#services:
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: thermoprops_frontend
#    ports:
#      - "80:80"
#    volumes:
#            - .:/app
#            - /app/node_modules
#    
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    container_name: thermoprops_backend
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./backend:/app
#    environment:
#      - FLASK_ENV=development
#
#networks:
#  mynetwork:
#    driver: bridge