"""create saturated_water table

Revision ID: 521ba53b9e0a
Revises: d46eddcfafda
Create Date: 2024-09-24 22:20:26.125063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521ba53b9e0a'
down_revision: Union[str, None] = 'd46eddcfafda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saturatedWaterTable',
    sa.Column('temperature_T', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('saturation_pressure_kPa', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('specific_volume_vf', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('specific_volume_vg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('internal_energy_uf', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('internal_energy_ufg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('internal_energy_ug', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('enthalpy_hf', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('enthalpy_hfg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('enthalpy_hg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('entropy_sf', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('entropy_sfg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('entropy_sg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('temperature_T')
    )
    op.create_index(op.f('ix_saturatedWaterTable_temperature_T'), 'saturatedWaterTable', ['temperature_T'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saturatedWaterTable_temperature_T'), table_name='saturatedWaterTable')
    op.drop_table('saturatedWaterTable')
    # ### end Alembic commands ###
